# Generated by Django 4.1.6 on 2023-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique favorite',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_name_measurement',
        ),
        migrations.RenameField(
            model_name='favoriterecipe',
            old_name='favorite_recipe',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#0055ff', max_length=7, verbose_name='Цветовой HEX-код'),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique favorite'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique name measurement'),
        ),
    ]
