# Generated by Django 4.1.6 on 2023-03-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_favoriterecipe_unique favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
